language: python
python: 2.7
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=check
    # - TOXENV=2.6,extension-coveralls,coveralls
    # - TOXENV=2.6-nocover
    - TOXENV=2.7,extension-coveralls,coveralls
    - TOXENV=2.7-nocover
    # - TOXENV=3.3,extension-coveralls,coveralls
    # - TOXENV=3.3-nocover
    # - TOXENV=3.4,extension-coveralls,coveralls
    # - TOXENV=3.4-nocover
    #- TOXENV=pypy,extension-coveralls,coveralls
    #- TOXENV=pypy-nocover
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip --update pip
  - pip install tox flake8
script:
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5d1581aa60471c78e1da
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

